
#===================================================
#============     BUILDING PIPELINE     ============
#===================================================

# Install project dependencies
install:
	@echo "Not done yet"

# Install project dependencies, including dev ones
install-dev:
	@echo "Not done yet"

# Build the project
build:
	@echo "Not done yet"

# Build the project in dev mode
build-dev:
	@echo "Not done yet"

# Run in production mode
run:
	@echo "Not done yet"

# Run in dev mode
run-dev:
	@echo "Not done yet"

#===================================================
#==================     TESTS     ==================
#===================================================

# Run unit tests
unit-tests:
	@echo "No unit tests yet"

# Run integration tests
integration-tests:
	@echo "No integration tests yet"

# Run all tests (unit + integration tests)
test:
	make unit-tests
	make integration-tests

#===================================================
#=============     CUSTOM COMMANDS     =============
#===================================================

# Add here custom commands
