version: '3'
services:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    jhipster-elasticsearch:
        build: jhipster-elasticsearch/
        ports:
            - "9200:9200"
        # Uncomment this section to have elasticsearch data loaded from a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data
    jhipster-logstash:
        build: jhipster-logstash/
        environment:
            - INPUT_TCP_PORT=5000
            - INPUT_UDP_PORT=5000
            - INPUT_HTTP_PORT=5001
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=true
        ports:
            - "5000:5000"
            - "5001:5001"
            - "9600:9600"
        depends_on:
            - jhipster-elasticsearch

    jhipster-console:
        build: jhipster-console/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        ports:
            - "5601:5601"
        depends_on:
            - jhipster-elasticsearch

    jhipster-import-dashboards:
        build: jhipster-import-dashboards/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        depends_on:
            - jhipster-elasticsearch

    # jhipster-alerter:
    #     build: jhipster-alerter/
    #     # Uncomment this section to enable alerting
    #     volumes:
    #         #- ./alerts/config.yaml:/opt/elastalert/config.yaml
    #         - ./alerts/rules/:/opt/elastalert/rules

    #https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configuration.html
    # jhipster-curator:
    #      build: jhipster-curator/
    #      environment:
    #          - ES_HOST=jhipster-elasticsearch
    #          - UNIT_COUNT=7
    #          - UNIT=days

    # jhipster-zipkin:
    #     build: jhipster-zipkin/
    #     environment:
    #         - ES_HOSTS=http://jhipster-elasticsearch:9200
    #         - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/discover/d0682f20-e0e9-11e7-9c68-0b9a0f0c183c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(X-B3-TraceId,app_name,level,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c7b73f10-e0e4-11e7-9c68-0b9a0f0c183c,key:logger_name,negate:!t,params:(query:metrics,type:phrase),type:phrase,value:metrics),query:(match:(logger_name:(query:metrics,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:X-B3-TraceId,negate:!f,params:(query:{traceId},type:phrase),type:phrase,value:{traceId}),query:(match:(X-B3-TraceId:(query:{traceId},type:phrase))))),index:'logstash-*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',asc))
    #     ports:
    #         - 9411:9411
