version: '2'
services:
    cassandra:
        image: cassandra:3.9
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        # volumes:
        #     - ./.volumes/{{ path }}/cassandra/:/var/lib/cassandra/data
