version: '2'
services:
    elasticsearch:
        image: elasticsearch:5.6.5-alpine
        ports:
            - 9200:9200
            - 9300:9300
        # volumes:
        #     - ./.volumes/{{ path }}/elasticsearch/:/usr/share/elasticsearch/data/
