version: '2'
services:
    mariadb:
        image: mariadb:10.1.17
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=test
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
        # volumes:
        #     - ./.volumes/{{ path }}/mysql/:/var/lib/mysql/
