version: '2'
services:
    postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
        # volumes:
        #     - ./.volumes/{{ path }}/postgresql/:/var/lib/postgresql/data/
